//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANHGIA
    {
        public int ID_CAP { get; set; }
        public int ID_CTTCHI { get; set; }
        public Nullable<double> TCHUAN_HOCTAP { get; set; }
        public Nullable<bool> TCHUAN_HD { get; set; }
    
        public virtual CAP CAP { get; set; }
        public virtual CT_TEUCHI CT_TEUCHI { get; set; }
    }
}
