//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUYET_TC
    {
        public int ID_SV { get; set; }
        public int ID_DANHGIA { get; set; }
        public Nullable<bool> DUYET { get; set; }
    
        public virtual DANHGIA DANHGIA { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
