//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOATDONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOATDONG()
        {
            this.THAMGIAs = new HashSet<THAMGIA>();
        }
    
        public int ID_HD { get; set; }
        public int ID_DV { get; set; }
        public string TenCT { get; set; }
        public Nullable<System.DateTime> NgayTC { get; set; }
        public string DiaDiemTC { get; set; }
        public int ID_CAP { get; set; }
        public int ID_TC { get; set; }
    
        public virtual CAP CAP { get; set; }
        public virtual DONVI DONVI { get; set; }
        public virtual TIEUCHI TIEUCHI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<THAMGIA> THAMGIAs { get; set; }
    }
}
