//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class NGUOIDUNG
    {
        public int ID_ND { get; set; }
        [Required(ErrorMessage ="Bạn chưa nhập tài khoản")]
        [StringLength(50, ErrorMessage = "Tên đăng nhập phải có ít nhất 6 ký tự", MinimumLength = 6)]
        public string TENDN { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập mật khẩu")]
        [StringLength(50,ErrorMessage ="Mật khẩu phải có ít nhất 6 ký tự",MinimumLength =6)]
        public string MK { get; set; }
        [Compare("MK",ErrorMessage ="Xác nhận mật khẩu không đúng")]
        public string XNMK { get; set; }
        [Required(ErrorMessage = "Bạn chưa nhập họ tên")]
        public string TENND { get; set; }
        public Nullable<bool> PQ { get; set; }
    }
}
