//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUOIDUNG
    {
        public int ID_ND { get; set; }
        public string TENDN { get; set; }
        public string MK { get; set; }
        public string TENND { get; set; }
        public Nullable<int> PQ { get; set; }
    }
}
