//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SINHVIEN
    {
        public int ID_SV { get; set; }
        public string TEN_SV { get; set; }
        public string LOP { get; set; }
        public string DIACHI { get; set; }
        public Nullable<int> SDT { get; set; }
        public string EMAIL { get; set; }
        public int ID_CAP { get; set; }
    
        public virtual CAP CAP { get; set; }
        public virtual THAMGIA THAMGIA { get; set; }
        public virtual TIEUCHI TIEUCHI { get; set; }
    }
}
