//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMGIA
    {
        public int ID_SV { get; set; }
        public int ID_HD { get; set; }
        public Nullable<System.DateTime> NGAY_HD { get; set; }
        public string XACNHAN { get; set; }
    
        public virtual HOATDONG HOATDONG { get; set; }
        public virtual SINHVIEN SINHVIEN { get; set; }
    }
}
