//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIEUCHI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIEUCHI()
        {
            this.CT_TEUCHI = new HashSet<CT_TEUCHI>();
        }
    
        public int ID_TCHI { get; set; }
        public string TEN_TCHI { get; set; }
        public int ID_LTCHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_TEUCHI> CT_TEUCHI { get; set; }
        public virtual LOAITIEUCHI LOAITIEUCHI { get; set; }
    }
}
