//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINTUC
    {
        public int ID_TT { get; set; }
        public string TITLE { get; set; }
        public string DETAIL { get; set; }
        public Nullable<System.DateTime> DATEBEGIN { get; set; }
        public string META { get; set; }
        public Nullable<int> ORDER { get; set; }
        public string LINK { get; set; }
        public Nullable<int> HIDE { get; set; }
    }
}
