//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACS_SV5T.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int ID_USER { get; set; }
        public string USERNAMES { get; set; }
        public string PASSWORD { get; set; }
        public string NAMES { get; set; }
        public Nullable<int> PERMISSION { get; set; }
    }
}
